---
title: "Leaves elongation"
author: "AJ Perez-Luque (@ajpelu)"
date: "2016 October"
output:  
    md_document:
      variant: markdown_github
      
---
# Analysis of Leaves elongation 

```{r metadata, echo=FALSE}
# Set working directory 

machine <- 'ajpelu'
machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/phd/phd_repos/qpyr_phenology', sep='')
```

```{r packages, warning=FALSE, echo=FALSE, message=FALSE}
# Load packages 
library("dplyr")
library("lubridate")
library("stringr")
library("ggplot2")


library("reshape2")

```

# Read and prepare data

```{r}
raw_elong <- read.table(file=paste(di, "/data_raw/elongacion.txt", sep= ""), header = TRUE, sep = ';', 
                      encoding = 'UTF-8')

elong <- raw_elong %>% 
  mutate(cota = substr(PARCELA, 1,2), 
         replica = substr(PARCELA, 3,4)) %>% 
  mutate(date = lubridate::date(as.Date(FECHA, format='%d/%m/%Y')), 
         year = lubridate::year(date), 
         yearF = as.factor(year), 
         cota = as.factor(cota),
         replica = as.factor(replica)) %>%
  select(loc = LOCALIDAD, 
        id_ind = COD_EJEMPLAR,
        rama = RAMA, 
        elongacion = LONG_ELONG, 
        cota, replica, date, year, yearF)

```

```{r}







library(lme4)


m1 <- glmer(elongacion ~ yearF + loc + cota + (1|replica), 
            family = poisson, data=elong)




m1 <- aov(elongacion ~ yearF*loc*cota, data=elong)

 glmer(cbind(incidence, size - incidence) ~ period +
(1 | herd) + (1|obs),
family = binomial, data = cbpp))


# Summary n 
n <- elong %>% 
  group_by(loc, cota, replica, year, id_ind) %>% 
  summarise(n= n(),
            media = mean(elongacion)) 

 
ggplot(n, aes(x=as.factor(year), y=media, group=replica, colour=replica)) + geom_boxplot(aes(group=year)) + facet_grid(cota~loc, scales = 'free')
```




